language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=pg_rollingwindow.py -m unittest2 discover
after_success:
  - coveralls